// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Check if current path is a public route that doesn't need Supabase
function isPublicRoute(): boolean {
  if (typeof window === 'undefined') return false;
  
  const path = window.location.pathname;
  return (
    path.startsWith('/reuniao/') ||
    path.startsWith('/reuniao-publica/') ||
    path.startsWith('/assinar/') ||
    path.startsWith('/f/') ||
    path.startsWith('/form/') ||
    path.startsWith('/formulario/') ||
    path.startsWith('/loja/') ||
    path.startsWith('/checkout/') ||
    path === '/' ||
    path === '/login' ||
    path === '/reseller-login' ||
    /^\/[^/]+\/form\//.test(path)
  );
}

// Import the supabase client like this:
// import { supabase } from "@/features/revendedora/integrations/supabase/client";

// Create a stub client if credentials are not available
const createSupabaseClient = () => {
  // Skip Supabase initialization on public routes
  if (isPublicRoute()) {
    return null as any;
  }
  
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    return null as any;
  }
  
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
};

export const supabase = createSupabaseClient();